### ISSUE TITLE
Design problem in using 20+ headers in horizontal scroll

### ISSUE THREAD

**Issue by deanilvincent** [xaksis/vue-good-table#162]
Good day,

I tried to use 20+ headers but the table footer isn't responsive.

The search box is stuck at the left side as well. 

![scrolltabletest](https://user-images.githubusercontent.com/10904957/35088163-c59626d4-fc6d-11e7-95e7-fa5526e45d4c.PNG)

Is there any fix for this? Thank you

**Comment by sorribes22** [comment]
I also have a problem related to the responsive.
When I see the table at the mobile phone I can't adjust the width to the mobile phone screen. If you found the solution to make it responsive share it please.

![screenshot_2018-01-22-12-31-36](https://user-images.githubusercontent.com/23049412/35218886-95c7c93e-ff70-11e7-87be-5512cfeb8fd7.png)

**Comment by rayets123** [comment]
Add styleClass="table-responsive"

**Comment by deanilvincent** [comment]
I don't know why, after I put that code in my styleClass, it's still the same. @rayets123

**Comment by xaksis** [comment]
@deanilvincent because that is a solution only for people using bootstrap. I'll try to put in a fix for this today. In the mean time, you can create your own class emulating what bootstrap does and pass it through :styleclass property: 
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_tables.scss

**Comment by deanilvincent** [comment]
@xaksis thank you for your quick response. I'll wait for the new version then. :)

**Comment by ModestasV** [comment]
Hello,

Unfortunately, we have come across the same issue too. Adding the table-responsive did not help at all.

http://prntscr.com/i7iix2 (Custom css applied for colors, rounded corners but even reverting it - has no affect to footer).

The main reason why we got this issue is that the footer is a different element all together http://prntscr.com/i7ik06 

Maybe anyone has an idea how to fix this? :)

**Comment by xaksis** [comment]
This should now be fixed in v1.19.2. Problem was introduced when pagination was separated from the main table rendering responsive class ineffective. closing.

**Comment by ModestasV** [comment]
@xaksis Can confirm that this issue was fixed after update for our project :)

Thank you!

**Comment by deanilvincent** [comment]
Hello @xaksis still, my header is the same even I already upgraded the vue-good-table to version 1.19.2

**Comment by deanilvincent** [comment]
@xaksis I can confirm that the footer is okay now. But the header position with search isn't fixed while scrolling horizontally.
