### ISSUE TITLE
TypeError: Cannot create property 'table-column' on boolean 'true'

### ISSUE THREAD

**Issue by ordinov** [xaksis/vue-good-table#504]
- [x] Bug

v.2.26.1

All my vue-good-table instances stopped running after 2.26.1 update - installing back 2.26.0 everything works fine.

> TypeError: Cannot create property 'table-column' on boolean 'true'

I tested also without defining settings, just with the basic example

**Comment by ow-en** [comment]
@ordinov can you please provide a fiddle reproducing the issue?

If so, I'd be happy to look into it further.

**Comment by ow-en** [comment]
So, looking into this further, it appears that vgt isn't available on cdnjs at the moment (which is what our example fiddle was using). @xaksis, any idea why it isn't showing up?

@ordinov if you were previously delivering the vue-good-table assets via cdnjs, you should be able to just swap out the cdn calls for (these)[https://www.jsdelivr.com/package/npm/vue-good-table] via jsDeliver.

**Comment by xaksis** [comment]
hey @ow-en what example are you referring to? the examples actually unpkg: https://unpkg.com/vue-good-table@2.16.1/dist/vue-good-table.js

I can actually reproduce @ordinov's error there. Going to look into this

**Comment by xaksis** [comment]
@ordinov @ow-en  so looks like this is breaking for all versions of vue older than 2.6 now.

**Comment by xaksis** [comment]
whoops, didn't mean to close it.

**Comment by xaksis** [comment]
looks like it was caused by an update to template compiler
https://github.com/xaksis/vue-good-table/commit/04ae9564d8304075dd71f7a2cc84d78bce48df27#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

which broke slots as they were used before vue 2.6. I have just released version with the correct configuration. @ordinov this should fix your build. I'll close the ticket when the change propagates to CDN

**Comment by ow-en** [comment]
Ah, got it. I must have been looking at the wrong place regarding the cdn. 

Related to #496, I needed to update to 2.6 to reproduce the checkbox issue, hence the update to the template compiler. Thanks for your help @xaksis.

**Comment by xaksis** [comment]
No worries! all examples are now working. We just need to update slot implementation before we move the plugin up to 2.6
👍 closing.

**Comment by Dave3of5** [comment]
I'm still getting this problem with 2.16.3 vue version 2.6.6 and vue-template-compiler 2.6.6.

What's the solution ?

**Comment by tirtasantoso** [comment]
Also encountering the same issue even with the basic example.

**Comment by xaksis** [comment]
@Dave3of5 @tirtasantoso could either of you create a fiddle to show this? I'm looking at the basic example here: https://jsfiddle.net/aks9800/dc1L3pza/2/ which uses vue 2.6.8 and it works fine as you can see. 

Are you sure the plugin isn't just cached for you?

**Comment by Dave3of5** [comment]
@xaksis Thanks for that example the update to vue 2.6.8 worked it wasn't working with 2.6.6 but I see that there have been changes in the slots code for 2.6.7 and 2.6.8 so I think that's what the problem was.

**Comment by biscuitRemark** [comment]
replaced  `import { VueGoodTable } from 'vue-good-table' ` with 
 `import { VueGoodTable } from 'vue-good-table/src'`
and the error is gone
